apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  version: {{ .Values.version }}
  count: {{ .Values.count }}
  elasticsearchRef:
    name: {{ .Values.elasticsearchRef }}
  podTemplate:
    spec:
      nodeSelector:
        role: infra
      containers:
        - name: kibana
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
  http:
    service:
      spec:
        type: ClusterIP
