apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: __NAMESPACE__
data:
  SPRING_APPLICATION_NAME: notification-service
  GRPC_CLIENT_HOST: localhost
  GRPC_CLIENT_PORT: "6565"
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  KAFKA_CONSUMER_GROUP: notification-email-consumer-v1
  KAFKA_LISTENER_CONCURRENCY: "6"
  KAFKA_MAX_POLL_RECORDS: "200"
  NOTIFICATION_TOPIC_MAIN: notification.email.v1
  NOTIFICATION_TOPIC_RETRY_1M: notification.email.retry.1m.v1
  NOTIFICATION_TOPIC_RETRY_5M: notification.email.retry.5m.v1
  NOTIFICATION_TOPIC_RETRY_30M: notification.email.retry.30m.v1
  NOTIFICATION_TOPIC_DLQ: notification.email.dlq.v1
  NOTIFICATION_RETRY_MAX_ATTEMPTS: "6"
  SMTP_MAX_IN_FLIGHT: "200"
  SMTP_PER_DOMAIN_RATE: "50"
