apiVersion: v1
kind: Service
metadata:
  name: node-project-template
  namespace: __NAMESPACE__
  labels:
    app: node-project-template
spec:
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  selector:
    app: node-project-template
  type: ClusterIP
