spring:
  application:
    name: generic-command-service

grpc:
  client:
    host: localhost
    port: 6565

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
