-- In Oracle, a Schema is tied to a User. 
-- Creating a user effectively creates a new, isolated sub-schema.

-- Switch session to the pluggable database (FREEPDB1)
ALTER SESSION SET CONTAINER = FREEPDB1;

-- ==========================================
-- 1. Create Schema for Account Service
-- ==========================================
CREATE USER account_schema IDENTIFIED BY account_pass QUOTA UNLIMITED ON USERS;

-- Grant necessary privileges
GRANT CONNECT, RESOURCE TO account_schema;
GRANT CREATE SESSION TO account_schema;
GRANT CREATE TABLE TO account_schema;
GRANT CREATE VIEW TO account_schema;

-- Create an example table inside the account schema
CREATE TABLE account_schema.users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert sample data
INSERT INTO account_schema.users (username, email) VALUES ('admin', 'admin@trading.local');
INSERT INTO account_schema.users (username, email) VALUES ('johndoe', 'john@example.com');
COMMIT;


-- ==========================================
-- 2. Create Schema for Order Service
-- ==========================================
CREATE USER order_schema IDENTIFIED BY order_pass QUOTA UNLIMITED ON USERS;

-- Grant necessary privileges
GRANT CONNECT, RESOURCE TO order_schema;
GRANT CREATE SESSION TO order_schema;
GRANT CREATE TABLE TO order_schema;

-- Create an example table inside the order schema
CREATE TABLE order_schema.orders (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id NUMBER NOT NULL,
    symbol VARCHAR2(10) NOT NULL,
    quantity NUMBER NOT NULL,
    price NUMBER(10, 2) NOT NULL,
    status VARCHAR2(20) DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert sample data
INSERT INTO order_schema.orders (account_id, symbol, quantity, price) VALUES (1, 'AAPL', 10, 150.00);
COMMIT;
