apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-price-feed-adapter
  namespace: __NAMESPACE__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-price-feed-adapter
  template:
    metadata:
      labels:
        app: node-price-feed-adapter
    spec:
      containers:
        - name: node-price-feed-adapter
          image: __IMAGE__
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
              name: node-price-feed-adapter-config
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
