# --- Oracle Database Configuration ---
quarkus.datasource.db-kind=oracle
quarkus.datasource.jdbc.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
quarkus.datasource.username=acme
quarkus.datasource.password=acme
quarkus.hibernate-orm.database.generation=update

# --- MongoDB Configuration ---
quarkus.mongodb.connection-string=mongodb://localhost:27017
quarkus.mongodb.database=acme_orders

# --- Redis Configuration ---
quarkus.redis.hosts=redis://localhost:6379

# --- Kafka Configuration ---
kafka.bootstrap.servers=localhost:9092

# Kafka
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# GraphQL
quarkus.smallrye-graphql.ui.always-include=true

# gRPC
quarkus.grpc.server.port=${GRPC_PORT:9090}

# Logging (JSON for ES)
quarkus.log.console.json=true
