apiVersion: v1
kind: ConfigMap
metadata:
  name: reporting-service-config
  namespace: __NAMESPACE__
data:
  SPRING_APPLICATION_NAME: reporting-service
  GRPC_CLIENT_HOST: localhost
  GRPC_CLIENT_PORT: "6565"
