apiVersion: v1
kind: Secret
metadata:
  name: gitlab-minio-secret
  namespace: gitlab
type: Opaque
stringData:
  connection: |
    provider: AWS
    region: us-east-1
    aws_access_key_id: "${MINIO_ROOT_USER}"
    aws_secret_access_key: "${MINIO_ROOT_PASSWORD}"
    aws_signature_version: 4
    host: minio.infra.svc
    endpoint: "http://minio.infra.svc:9000"
    path_style: true
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry-storage
  namespace: gitlab
type: Opaque
stringData:
  config: |
    s3:
      bucket: gitlab-registry
      accesskey: "${MINIO_ROOT_USER}"
      secretkey: "${MINIO_ROOT_PASSWORD}"
      regionendpoint: http://minio.infra.svc:9000
      region: us-east-1
      secure: false
      v4auth: true
      pathstyle: true
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-root-password
  namespace: gitlab
type: Opaque
stringData:
  password: "${GITLAB_ROOT_PASSWORD}"
